name: Cross Browser Selenium Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, edge]

    env:
      BROWSER: ${{ matrix.browser }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Set up Maven
        run: sudo apt-get install -y maven

      - name: Install Dependencies
        run: mvn install -DskipTests

      - name: Run TestNG Tests on ${{ matrix.browser }}
        run: mvn test -Dbrowser=${{ matrix.browser }}

      - name: Archive Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: testng-reports-${{ matrix.browser }}
          path: test-output/
