name: Run Selenium TestNG Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install Maven
        run: sudo apt-get install maven -y

      - name: Install required browsers
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y microsoft-edge-stable || true  # Edge might not be available on all runners

      - name: Display browser versions (for debugging)
        run: |
          google-chrome --version || true
          microsoft-edge --version || true

      - name: Run Maven Tests with TestNG Suite
        run: mvn clean test

      - name: Show test failures (if any)
        if: failure()
        run: cat target/surefire-reports/*.txt || true

      - name: Upload Surefire Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Surefire-Test-Report
          path: target/surefire-reports/

      - name: Upload TestNG Output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestNG-test-output
          path: test-output/
