name: Run Selenium TestNG Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Build and Run Tests
        run: mvn clean test

      #  test result logs on failure
      - name: Show test report if tests fail
        if: failure()
        run: cat target/surefire-reports/*.txt || true

      # Surefire test report (test result logs)
      - name: Upload Surefire Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Surefire-test-report
          path: target/surefire-reports/

      # TestNG test-output folder if it exists
      - name: Upload TestNG test-output folder
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestNG-test-output
          path: test-output/
